name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Fork
        run: npm run ganache:fork &
        env:
          PUBLIC_ADDRESS: ${{ secrets.PUBLIC_ADDRESS }}
          ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}

      - name: Tests
        run: npm run test -- --runInBand --detectOpenHandles --forceExit
        env:
          PUBLIC_ADDRESS: ${{ secrets.PUBLIC_ADDRESS }}
          ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}